// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZU0V_Rrj8UU3T9tgMHk4UDccE9xh89Ok',
    appId: '1:322776951600:web:19136a5c536c6166f5f6f5',
    messagingSenderId: '322776951600',
    projectId: 'haseela-95ea5',
    authDomain: 'haseela-95ea5.firebaseapp.com',
    storageBucket: 'haseela-95ea5.firebasestorage.app',
    measurementId: 'G-ENKCPMZTL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL90dIxi5ec46mz7s5miEAMQ5z6_P80YU',
    appId: '1:322776951600:android:7328b6fca2ffa7ebf5f6f5',
    messagingSenderId: '322776951600',
    projectId: 'haseela-95ea5',
    storageBucket: 'haseela-95ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0TFIeWxE03JDZcTSMATbfuP7hV0aF8M',
    appId: '1:322776951600:ios:b56376d31981e19ff5f6f5',
    messagingSenderId: '322776951600',
    projectId: 'haseela-95ea5',
    storageBucket: 'haseela-95ea5.firebasestorage.app',
    iosBundleId: 'com.example.haseelaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0TFIeWxE03JDZcTSMATbfuP7hV0aF8M',
    appId: '1:322776951600:ios:b56376d31981e19ff5f6f5',
    messagingSenderId: '322776951600',
    projectId: 'haseela-95ea5',
    storageBucket: 'haseela-95ea5.firebasestorage.app',
    iosBundleId: 'com.example.haseelaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZU0V_Rrj8UU3T9tgMHk4UDccE9xh89Ok',
    appId: '1:322776951600:web:6b6054cc22dbb38cf5f6f5',
    messagingSenderId: '322776951600',
    projectId: 'haseela-95ea5',
    authDomain: 'haseela-95ea5.firebaseapp.com',
    storageBucket: 'haseela-95ea5.firebasestorage.app',
    measurementId: 'G-MQN4F6W7F6',
  );
}
